opensrp-anc/src/main/AndroidManifest.xml
opensrp-anc/src/main/java/org/smartregister/anc/activity/BaseProfileActivity.java
opensrp-anc/src/main/java/org/smartregister/anc/activity/ProfileActivity.java
opensrp-anc/src/main/java/org/smartregister/anc/contract/ProfileContract.java
opensrp-anc/src/main/java/org/smartregister/anc/presenter/ProfilePresenter.java
opensrp-anc/src/main/java/org/smartregister/anc/util/Constants.java
opensrp-anc/src/main/java/org/smartregister/anc/view/CopyToClipboardDialog.java
opensrp-anc/src/main/res/drawable/copy_to_clipboard_background.xml
opensrp-anc/src/main/res/layout/widget_copy_to_clipboard.xml
opensrp-anc/src/main/res/values-sw600dp/dimens.xml
opensrp-anc/src/main/res/values/colors.xml
opensrp-anc/src/main/res/values/dimens.xml
opensrp-anc/src/main/res/values/strings.xml
opensrp-anc/src/main/res/values/styles.xml
opensrp-anc/src/test/java/org/smartregister/anc/activity/ProfileActivityTest.java
opensrp-anc/src/test/java/org/smartregister/anc/presenter/ProfilePresenterTest.java
opensrp-anc/src/test/java/org/smartregister/anc/view/CopyToClipboardDialogTest.java

#[Issue27 # ]( https://github.com/OpenSRP/opensrp-client-anc/issues/2)7

Implement profile menu in top right

---

README.md
opensrp-anc/src/main/java/org/smartregister/anc/activity/BaseRegisterActivity.java
opensrp-anc/src/main/java/org/smartregister/anc/contract/RegisterContract.java
opensrp-anc/src/main/java/org/smartregister/anc/domain/AttentionFlag.java
opensrp-anc/src/main/java/org/smartregister/anc/fragment/BaseRegisterFragment.java
opensrp-anc/src/main/java/org/smartregister/anc/fragment/HomeRegisterFragment.java
opensrp-anc/src/main/java/org/smartregister/anc/provider/RegisterProvider.java
opensrp-anc/src/main/res/drawable/round_red_background.xml
opensrp-anc/src/main/res/drawable/round_yellow_background.xml
opensrp-anc/src/main/res/layout/alert_dialog_attention_flag.xml
opensrp-anc/src/main/res/layout/alert_dialog_attention_flag_row_red.xml
opensrp-anc/src/main/res/layout/alert_dialog_attention_flag_row_yellow.xml
opensrp-anc/src/main/res/values/dimens.xml
opensrp-anc/src/main/res/values/strings.xml
opensrp-anc/src/test/java/org/smartregister/anc/activity/BaseUnitTest.java
opensrp-anc/src/test/java/org/smartregister/anc/activity/HomeRegisterActivityTest.java

https://github.com/OpenSRP/opensrp-client-anc/issues/24

Implement attention flag popup functionality #24

---

opensrp-anc/src/main/AndroidManifest.xml
opensrp-anc/src/main/java/org/smartregister/anc/activity/ContactSummaryActivity.java
opensrp-anc/src/main/java/org/smartregister/anc/adapter/ContactSummaryAdapter.java
opensrp-anc/src/main/java/org/smartregister/anc/contract/BaseContactContract.java
opensrp-anc/src/main/java/org/smartregister/anc/contract/ContactContract.java
opensrp-anc/src/main/java/org/smartregister/anc/contract/ContactSummaryContract.java
opensrp-anc/src/main/java/org/smartregister/anc/fragment/MeFragment.java
opensrp-anc/src/main/java/org/smartregister/anc/interactor/BaseContactInteractor.java
opensrp-anc/src/main/java/org/smartregister/anc/interactor/ContactInteractor.java
opensrp-anc/src/main/java/org/smartregister/anc/interactor/ContactSummaryInteractor.java
opensrp-anc/src/main/java/org/smartregister/anc/model/BaseContactModel.java
opensrp-anc/src/main/java/org/smartregister/anc/model/ContactModel.java
opensrp-anc/src/main/java/org/smartregister/anc/model/ContactSummaryModel.java
opensrp-anc/src/main/java/org/smartregister/anc/presenter/ContactPresenter.java
opensrp-anc/src/main/java/org/smartregister/anc/presenter/ContactSummaryPresenter.java
opensrp-anc/src/main/java/org/smartregister/anc/presenter/LoginPresenter.java
opensrp-anc/src/main/java/org/smartregister/anc/util/Constants.java
opensrp-anc/src/main/res/drawable/blue_button.xml
opensrp-anc/src/main/res/layout/activity_contact_summary.xml
opensrp-anc/src/main/res/layout/fragment_me.xml
opensrp-anc/src/main/res/layout/partial_contact_dates.xml
opensrp-anc/src/main/res/values/colors.xml
opensrp-anc/src/main/res/values/strings.xml
opensrp-anc/src/test/java/org/smartregister/anc/activity/ContactSummaryActivityTest.java
opensrp-anc/src/test/java/org/smartregister/anc/interactor/ContactInteractorTest.java
opensrp-anc/src/test/java/org/smartregister/anc/interactor/ContactSummaryInteractorTest.java
opensrp-anc/src/test/java/org/smartregister/anc/model/ContactSummaryModelTest.java
opensrp-anc/src/test/java/org/smartregister/anc/presenter/ContactPresenterTest.java
opensrp-anc/src/test/java/org/smartregister/anc/presenter/ContactSummaryPresenterTest.java

Implement contact submission confirmation page

---

opensrp-anc/src/main/assets/json.form/anc_profile.json
opensrp-anc/src/main/assets/json.form/anc_site_characteristics.json
opensrp-anc/src/main/java/org/smartregister/anc/fragment/AdvancedSearchFragment.java
opensrp-anc/src/main/res/layout/activity_profile.xml
opensrp-anc/src/main/res/layout/advanced_search_list.xml

Fix the search result `# matches` alignment 
Fix the person profile transition 
Fix some missing profile form relevance

Fix a couple of QA fixes

---

README.md
opensrp-anc/src/main/java/org/smartregister/anc/activity/BaseContactActivity.java
opensrp-anc/src/main/java/org/smartregister/anc/activity/ContactJsonFormActivity.java
opensrp-anc/src/main/java/org/smartregister/anc/contract/ContactContract.java
opensrp-anc/src/main/java/org/smartregister/anc/interactor/QuickCheckInteractor.java
opensrp-anc/src/main/java/org/smartregister/anc/model/PartialContact.java
opensrp-anc/src/main/java/org/smartregister/anc/presenter/ContactPresenter.java
opensrp-anc/src/main/java/org/smartregister/anc/repository/PartialContactRepository.java
opensrp-anc/src/main/java/org/smartregister/anc/repository/PatientRepository.java
opensrp-anc/src/main/java/org/smartregister/anc/util/Constants.java
opensrp-anc/src/test/java/org/smartregister/anc/presenter/ContactPresenterTest.java
opensrp-anc/src/test/java/org/smartregister/anc/repository/PatientRepositoryTest.java

Implement save contact draft autosave feature

---

opensrp-anc/build.gradle
opensrp-anc/src/main/java/org/smartregister/anc/activity/HomeRegisterActivity.java
opensrp-anc/src/main/java/org/smartregister/anc/activity/LoginActivity.java
opensrp-anc/src/main/java/org/smartregister/anc/activity/ProfileActivity.java
opensrp-anc/src/main/java/org/smartregister/anc/application/AncApplication.java
opensrp-anc/src/main/java/org/smartregister/anc/contract/RegisterFragmentContract.java
opensrp-anc/src/main/java/org/smartregister/anc/fragment/AdvancedSearchFragment.java
opensrp-anc/src/main/java/org/smartregister/anc/fragment/HomeRegisterFragment.java
opensrp-anc/src/main/java/org/smartregister/anc/fragment/QuickCheckFragment.java
opensrp-anc/src/main/java/org/smartregister/anc/helper/ECSyncHelper.java
opensrp-anc/src/main/java/org/smartregister/anc/model/MeModel.java
opensrp-anc/src/main/java/org/smartregister/anc/model/RegisterModel.java
opensrp-anc/src/main/java/org/smartregister/anc/provider/AdvancedSearchProvider.java
opensrp-anc/src/main/java/org/smartregister/anc/provider/RegisterProvider.java
opensrp-anc/src/main/java/org/smartregister/anc/util/JsonFormUtils.java
opensrp-anc/src/main/java/org/smartregister/anc/util/Utils.java
opensrp-anc/src/test/java/org/smartregister/anc/model/MeModelTest.java
opensrp-anc/src/test/java/org/smartregister/anc/model/RegisterModelTest.java
opensrp-anc/src/test/java/org/smartregister/anc/util/UtilsTest.java

- Added method to customize bottom navigation
- Updated Utils class to extend core's Utils class
- Moved common methods to core's Utils class
- Moved common methods to core's sync helper class

Update after core 121

---

opensrp-anc/src/main/assets/rule/sf_relevance_rules.yml

Change relevance logic for varicose veins or oedema other symptoms

---

opensrp-anc/src/main/assets/json.form/anc_physical_exam.json
opensrp-anc/src/main/assets/rule/physical-exam-relevance-rules.yml

Change relevance logic for fetal heartbeat present field in PE container

---

opensrp-anc/src/main/assets/json.form/sub_form/tests_blood_haemoglobin_sub_form.json
opensrp-anc/src/main/assets/rule/tests_calculation_rules.yml
opensrp-anc/src/main/java/org/smartregister/anc/library/util/ContactJsonFormUtils.java

Fix Anaemia diagnosis alert logic in Haemoglobin test expansion panel

---

opensrp-anc/build.gradle
reference-app/build.gradle

* update the versioning function

* update the sql cipher library version to the same one used on core

---

opensrp-anc/build.gradle
opensrp-anc/src/main/assets/json.form/sub_form/tests_ultrasound_sub_form.json
opensrp-anc/src/main/assets/rule/ct_relevance_rules.yml
opensrp-anc/src/main/assets/rule/ultrasound_sub_form_relevance_rules.yml
reference-app/build.gradle

Remove the gestational age condition on the first TT dose

---

opensrp-anc/build.gradle
opensrp-anc/src/main/assets/json.form/anc_counselling_treatment.json
opensrp-anc/src/main/assets/json.form/anc_physical_exam.json
opensrp-anc/src/main/assets/json.form/anc_profile.json
opensrp-anc/src/main/assets/json.form/anc_quick_check.json
opensrp-anc/src/main/assets/json.form/anc_site_characteristics.json
opensrp-anc/src/main/assets/json.form/anc_symptoms_follow_up.json
opensrp-anc/src/main/assets/json.form/anc_test.json
opensrp-anc/src/main/java/org/smartregister/anc/library/fragment/ContactJsonFormFragment.java
opensrp-anc/src/test/java/org/smartregister/anc/library/fragment/ContactJsonFormFragmentTest.java
reference-app/build.gradle

Add scroll bar to contact container pages

---

opensrp-anc/src/main/assets/json.form/anc_profile.json
opensrp-anc/src/main/assets/rule/profile_calculation_rules.yml
opensrp-anc/src/main/assets/rule/profile_relevance_rules.yml

Add constraint logic to select preferred

---

opensrp-anc/src/main/assets/rule/ct_relevance_rules.yml

Fix calculation/relevance logic in C&T

---

opensrp-anc/src/main/assets/json.form/anc_profile.json

Change the constraint on the LMP date in Profile

---

opensrp-anc/src/main/assets/json.form/anc_counselling_treatment.json
opensrp-anc/src/main/assets/json.form/anc_profile.json
opensrp-anc/src/main/assets/json.form/anc_symptoms_follow_up.json
opensrp-anc/src/main/assets/rule/ct_relevance_rules.yml
opensrp-anc/src/main/assets/rule/profile_relevance_rules.yml
opensrp-anc/src/main/assets/rule/sf_calculation_rules.yml
opensrp-anc/src/main/assets/rule/sf_relevance_rules.yml

- Updated counselling & treatment
- Anc profile
- Anc symptoms and follow up

Updates to rules and calculations

---

opensrp-anc/build.gradle
reference-app/build.gradle

Fix Issue #627

---

opensrp-anc/src/main/java/org/smartregister/anc/library/activity/BaseHomeRegisterActivity.java

Fix issue 687

---

opensrp-anc/src/main/assets/json.form/anc_profile.json

Issue https://github.com/opensrp/opensrp-client-anc/issues/703 resolved

Anc issue 703

---

opensrp-anc/src/main/java/org/smartregister/anc/library/presenter/RegisterPresenter.java

dialog does not display after registering the new mother issue resolved
